# Generated by Django 5.1.4 on 2025-08-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TireApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.IntegerField(verbose_name='Радиус (дюймы)')),
                ('width', models.IntegerField(verbose_name='Ширина (мм)')),
                ('profile_height', models.IntegerField(verbose_name='Высота профиля (%)')),
                ('season', models.CharField(choices=[('summer', 'Летние'), ('winter', 'Зимние'), ('all_season', 'Всесезонные')], max_length=20, verbose_name='Сезон')),
                ('spikes', models.CharField(choices=[('with_spikes', 'С шипами'), ('without_spikes', 'Без шипов')], max_length=20, verbose_name='Шипы')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Заявка на шины',
                'verbose_name_plural': 'Заявки на шины',
                'ordering': ['-created_at'],
            },
        ),
    ]
