# Generated by Django 5.1.4 on 2025-08-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tireapplication',
            name='service_type',
            field=models.CharField(blank=True, choices=[('tire-replacement', 'Замена шин'), ('tire-repair', 'Ремонт шин'), ('tire-balancing', 'Балансировка колес'), ('seasonal-change', 'Сезонная смена шин')], max_length=50, null=True, verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='tireapplication',
            name='profile_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота профиля (%)'),
        ),
        migrations.AlterField(
            model_name='tireapplication',
            name='radius',
            field=models.IntegerField(blank=True, null=True, verbose_name='Радиус (дюймы)'),
        ),
        migrations.AlterField(
            model_name='tireapplication',
            name='season',
            field=models.CharField(blank=True, choices=[('summer', 'Летние'), ('winter', 'Зимние'), ('all_season', 'Всесезонные')], max_length=20, null=True, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='tireapplication',
            name='spikes',
            field=models.CharField(blank=True, choices=[('with_spikes', 'С шипами'), ('without_spikes', 'Без шипов')], max_length=20, null=True, verbose_name='Шипы'),
        ),
        migrations.AlterField(
            model_name='tireapplication',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина (мм)'),
        ),
    ]
