# Generated by Django 5.1.4 on 2025-08-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0002_tireapplication_service_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(choices=[('summer', 'Летние шины'), ('winter', 'Зимние шины'), ('all_season', 'Всесезонные'), ('suv', 'Внедорожники'), ('passenger', 'Легковые')], max_length=20, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Изображение')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер')),
                ('brand', models.CharField(default='Nokian', max_length=100, verbose_name='Бренд')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемые')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='tireapplication',
            name='service_type',
        ),
        migrations.AlterField(
            model_name='tireapplication',
            name='profile_height',
            field=models.IntegerField(default=1, verbose_name='Высота профиля (%)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tireapplication',
            name='radius',
            field=models.IntegerField(default=1, verbose_name='Радиус (дюймы)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tireapplication',
            name='season',
            field=models.CharField(choices=[('summer', 'Летние'), ('winter', 'Зимние'), ('all_season', 'Всесезонные')], default=1, max_length=20, verbose_name='Сезон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tireapplication',
            name='spikes',
            field=models.CharField(choices=[('with_spikes', 'С шипами'), ('without_spikes', 'Без шипов')], default=1, max_length=20, verbose_name='Шипы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tireapplication',
            name='width',
            field=models.IntegerField(default=1, verbose_name='Ширина (мм)'),
            preserve_default=False,
        ),
    ]
