# Generated by Django 5.1.4 on 2025-08-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0003_portfolioitem_remove_tireapplication_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(choices=[('summer', 'Летние шины'), ('winter', 'Зимние шины'), ('all_season', 'Всесезонные'), ('suv', 'SUV/Внедорожники'), ('passenger', 'Легковые')], max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tireapplication',
            name='profile_height',
            field=models.IntegerField(default=65, verbose_name='Высота профиля (%)'),
        ),
    ]
