# Generated by Django 5.2.5 on 2025-08-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0004_alter_portfolioitem_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tireapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на подбор шин', 'verbose_name_plural': 'Заявки на подбор шин'},
        ),
        migrations.RemoveField(
            model_name='tireapplication',
            name='profile_height',
        ),
        migrations.RemoveField(
            model_name='tireapplication',
            name='radius',
        ),
        migrations.RemoveField(
            model_name='tireapplication',
            name='spikes',
        ),
        migrations.RemoveField(
            model_name='tireapplication',
            name='width',
        ),
        migrations.AddField(
            model_name='tireapplication',
            name='budget',
            field=models.CharField(blank=True, choices=[('economy', 'До 15,000₽'), ('optimum', '15-25,000₽'), ('premium', '25,000₽+')], max_length=20, null=True, verbose_name='Бюджет'),
        ),
        migrations.AddField(
            model_name='tireapplication',
            name='car_make',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='tireapplication',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='tireapplication',
            name='priority',
            field=models.CharField(blank=True, choices=[('safety', 'Безопасность'), ('comfort', 'Комфорт'), ('sport', 'Спорт'), ('economy', 'Экономия')], max_length=20, null=True, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='tireapplication',
            name='selection_type',
            field=models.CharField(choices=[('by_size', 'Подбор по размерам'), ('by_car', 'Подбор по автомобилю')], default=1, max_length=20, verbose_name='Тип подбора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tireapplication',
            name='telegram_contact',
            field=models.BooleanField(default=False, verbose_name='Контакт через Telegram'),
        ),
        migrations.AddField(
            model_name='tireapplication',
            name='tire_profile',
            field=models.IntegerField(blank=True, null=True, verbose_name='Профиль шины (%)'),
        ),
        migrations.AddField(
            model_name='tireapplication',
            name='tire_radius',
            field=models.IntegerField(blank=True, null=True, verbose_name='Радиус шины (дюймы)'),
        ),
        migrations.AddField(
            model_name='tireapplication',
            name='tire_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина шины (мм)'),
        ),
        migrations.AddField(
            model_name='tireapplication',
            name='whatsapp_contact',
            field=models.BooleanField(default=False, verbose_name='Контакт через WhatsApp'),
        ),
        migrations.AddField(
            model_name='tireapplication',
            name='winter_type',
            field=models.CharField(blank=True, choices=[('studded', 'Шипы'), ('friction', 'Липучка')], max_length=20, null=True, verbose_name='Тип зимних шин'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(choices=[('summer', 'Летние шины'), ('winter', 'Зимние шины'), ('all_season', 'Всесезонные'), ('suv', 'Внедорожники'), ('passenger', 'Легковые')], max_length=20, verbose_name='Категория'),
        ),
    ]
