# Generated by Django 5.2.5 on 2025-08-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0005_alter_tireapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tireapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на шины', 'verbose_name_plural': 'Заявки на шины'},
        ),
        migrations.RemoveField(
            model_name='tireapplication',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='tireapplication',
            name='car_make',
        ),
        migrations.RemoveField(
            model_name='tireapplication',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='tireapplication',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='tireapplication',
            name='selection_type',
        ),
        migrations.RemoveField(
            model_name='tireapplication',
            name='telegram_contact',
        ),
        migrations.RemoveField(
            model_name='tireapplication',
            name='tire_profile',
        ),
        migrations.RemoveField(
            model_name='tireapplication',
            name='tire_radius',
        ),
        migrations.RemoveField(
            model_name='tireapplication',
            name='tire_width',
        ),
        migrations.RemoveField(
            model_name='tireapplication',
            name='whatsapp_contact',
        ),
        migrations.RemoveField(
            model_name='tireapplication',
            name='winter_type',
        ),
        migrations.AddField(
            model_name='tireapplication',
            name='profile_height',
            field=models.IntegerField(default=65, verbose_name='Высота профиля (%)'),
        ),
        migrations.AddField(
            model_name='tireapplication',
            name='radius',
            field=models.IntegerField(default=1, verbose_name='Радиус (дюймы)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tireapplication',
            name='spikes',
            field=models.CharField(choices=[('with_spikes', 'С шипами'), ('without_spikes', 'Без шипов')], default=1, max_length=20, verbose_name='Шипы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tireapplication',
            name='width',
            field=models.IntegerField(default=1, verbose_name='Ширина (мм)'),
            preserve_default=False,
        ),
    ]
