# Generated by Django 5.2.5 on 2025-08-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0006_alter_tireapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tireapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на подбор шин', 'verbose_name_plural': 'Заявки на подбор шин'},
        ),
        migrations.RemoveField(
            model_name='tireapplication',
            name='profile_height',
        ),
        migrations.RemoveField(
            model_name='tireapplication',
            name='radius',
        ),
        migrations.RemoveField(
            model_name='tireapplication',
            name='spikes',
        ),
        migrations.RemoveField(
            model_name='tireapplication',
            name='width',
        ),
        migrations.AddField(
            model_name='tireapplication',
            name='budget',
            field=models.CharField(choices=[('economy', 'До 15,000₽'), ('optimum', '15-25,000₽'), ('premium', '25,000₽+')], default=1, max_length=20, verbose_name='Бюджет на комплект'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tireapplication',
            name='car_make',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='tireapplication',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='tireapplication',
            name='priority',
            field=models.CharField(choices=[('safety', 'Безопасность'), ('comfort', 'Комфорт'), ('sport', 'Спорт'), ('economy', 'Экономия')], default=1, max_length=20, verbose_name='Приоритет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tireapplication',
            name='selection_type',
            field=models.CharField(choices=[('by_size', 'Подбор по размерам'), ('by_car', 'Подбор по автомобилю')], default=1, max_length=20, verbose_name='Способ подбора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tireapplication',
            name='tire_profile',
            field=models.IntegerField(blank=True, null=True, verbose_name='Профиль шины (%)'),
        ),
        migrations.AddField(
            model_name='tireapplication',
            name='tire_radius',
            field=models.IntegerField(blank=True, null=True, verbose_name='Радиус шины (дюймы)'),
        ),
        migrations.AddField(
            model_name='tireapplication',
            name='tire_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина шины (мм)'),
        ),
        migrations.AddField(
            model_name='tireapplication',
            name='winter_type',
            field=models.CharField(blank=True, choices=[('spikes', 'Шипы'), ('friction', 'Липучка')], max_length=20, null=True, verbose_name='Тип зимних шин'),
        ),
        migrations.AlterField(
            model_name='tireapplication',
            name='season',
            field=models.CharField(choices=[('summer', 'Летние'), ('winter', 'Зимние'), ('all_season', 'Всесезонные')], max_length=20, verbose_name='Сезон использования'),
        ),
    ]
