# Generated by Django 5.1.4 on 2025-08-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0007_alter_tireapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tireapplication',
            name='budget',
            field=models.CharField(choices=[('economy', 'До 15,000₽'), ('optimum', '15-25,000₽'), ('premium', '25,000₽+')], default='optimum', max_length=20, verbose_name='Бюджет на комплект'),
        ),
        migrations.AlterField(
            model_name='tireapplication',
            name='priority',
            field=models.CharField(choices=[('safety', 'Безопасность'), ('comfort', 'Комфорт'), ('sport', 'Спорт'), ('economy', 'Экономия')], default='comfort', max_length=20, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='tireapplication',
            name='season',
            field=models.CharField(choices=[('summer', 'Летние'), ('winter', 'Зимние'), ('all_season', 'Всесезонные')], default='summer', max_length=20, verbose_name='Сезон использования'),
        ),
        migrations.AlterField(
            model_name='tireapplication',
            name='selection_type',
            field=models.CharField(choices=[('by_size', 'Подбор по размерам'), ('by_car', 'Подбор по автомобилю')], default='by_car', max_length=20, verbose_name='Способ подбора'),
        ),
    ]
