# Generated by Django 5.1.4 on 2025-08-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0008_alter_tireapplication_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(choices=[('all', 'Все шины'), ('summer', 'Летние шины'), ('winter', 'Зимние шины'), ('all_season', 'Всесезонные'), ('suv', 'Внедорожники')], default='all', max_length=20, verbose_name='Категория'),
        ),
    ]
